### ISSUE TITLE
endeitru.txt and en-de-it-ru.txt: Trained or Not?

### ISSUE THREAD

**Issue by liutianlin0121** [nmrksic/attract-repel#1]
Hi, 

Thanks for open source the codes for Attract-Repel! I have one question for the code.

In the experiment_parameters.cfg file,  you specified the distributional vectors  word-vectors/endeitru.txt. I assume that this is the set of row word vectors (from GloVe or other sources) that are NOT trained by Attract-Repel yet. It seems that this file endeitru.txt is not provided in this code release.

You did provide another file en-de-it-ru.txt.tar.gz here https://drive.google.com/file/d/0B_pyA_IW4g-jZzBIZXpYS1RseFk/view  However, after I tried it out, I think perhaps this is the set of the TRAINED vector with Attract-Repel, because the results seem super good even without running the Attract-Repel iterations. I wonder if you would verify that? 

Thanks in advance!

Best
Tianlin

**Comment by jatinganhotra** [comment]
@liutianlin0121 Were you able to reproduce the results using pre-trained Glove, as the `endeitru.txt` file specified is not available?

**Comment by liutianlin0121** [comment]
> @liutianlin0121 Were you able to reproduce the results using pre-trained Glove, as the `endeitru.txt` file specified is not available?

@jatinganhotra Hi, I did not try it.
